CREATE TABLE IF NOT EXISTS Player (
    PlayerId INTEGER NOT NULL PRIMARY KEY,
    Name TEXT
);

CREATE TABLE IF NOT EXISTS Game (
    GameId INTEGER NOT NULL PRIMARY KEY,
    PlayerId INTEGER NOT NULL,
    NumberOfAttempts INTEGER
);